### ISSUE TITLE
Garmoticz error switch not flipping or selecteable. 

### ISSUE THREAD

**Issue by ggamehdtv** [akamming/Garmoticz#1]
Hello,

I installed the garmoticz widget on the Garmin Fenix 5 plus but long clicking the enter switch is not working. It doesn't select or flip it. Is this a bug?

Hope you can help me :)

Greetz Justinn

**Comment by akamming** [comment]
I added some code, so now more types of switches can be flipped. Could you update to latest version and retry?

**Comment by ggamehdtv** [comment]
I updated and tried to change switch state. Its working now! thank you,  awesome app for the garmin watch :)
