### ISSUE TITLE
Broken with Domoticz 2023.2

### ISSUE THREAD

**Issue by mpavot** [akamming/Garmoticz#10]
Hello

API has changed in Domoticz 2023.2:
https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Warning_Stable_2023.2_.28and_newer.29

Using the old API is supposed to generate a Warning and still work but apparently the HTTP reply has slightly changed (in particular the 'title' tag which has changed from 'plans' to 'getplans' for instance).
With this change Garmoticz is not working anymore, I get a "Reponse HTTP inconnue"/"Unknown HTTP reply" error when Garmoticz tries to receive the list of rooms.

Marc

**Comment by mpavot** [comment]
I have submitted a PR to fix this: It doesn't switch to the new API (to not break users still using the old one) but it makes Garmoticz compatible with the replies from both versions.

**Comment by Losje** [comment]
Please support this change @akamming ; I'm another user who's affected :)

**Comment by gb78500** [comment]
If you use Apache as a reverse proxy, you can add something like :
<Location /domoticz/>
AddOutputFilterByType INFLATE;SUBSTITUTE;DEFLATE text/html application/json
Substitute "s/\"title\" : \"getplans\"/\"title\" : \"Plans\"/ni"
</Location>

The body of the response will be modified.

**Comment by akamming** [comment]
fixed with new update in connectiq store

**Comment by Losje** [comment]
Tested and working! Thanks!  @akamming
