### ISSUE TITLE
Unable to control VivoActive 3

### ISSUE THREAD

**Issue by karstenbakker** [akamming/Garmoticz#4]
Hi,

Currently I am unable to control any of the ligths in the house through the Garmin VivoActive 3. The only ones that are working are the on/off switches for the wall outlets. I included the json code from "https://ip/json.htm?type=devices&rid=34"  in the attachment.

Hopefully you know what seems te be the issue on any other devices samsung gear s3 it works fine.

[workingswitchoutlet.txt](https://github.com/akamming/Garmoticz/files/4113586/workingswitchoutlet.txt)

[notworkinglight.txt](https://github.com/akamming/Garmoticz/files/4113587/notworkinglight.txt)

**Comment by akamming** [comment]
hi, 

thanks for reporting. The reason they are not working i cause íve not yet implemented dimmer support. using your output i can build this feature (i have no dimmers myself) when i have some spare time.

If you happen to be a developer: Feel free to develop yourself (and make a PR)

**Comment by akamming** [comment]
i've made a simple solution for dimmers. Was less work than i expected. I hope it works this way. Can you upgrade to latest version and let me know the results?

**Comment by akamming** [comment]
no response, closing the issue...

**Comment by karstenbakker** [comment]
Thanks, forgot to respond will let the users know!
