### ISSUE TITLE
network time out -400

### ISSUE THREAD

**Issue by adrienvia** [akamming/Garmoticz#8]
Hi, i'm stuck with this error when I open the widget

at the beginning i was struggling with the -300 issue, but, i was able to make a certificate (it's working when i test it on another device)

and now, I don't know what is the problem. no explication for -400 error.

thanks.

I have a fenix 6X, and domoticz on a Pi3

**Comment by adrienvia** [comment]
i'm still stuck with this error, I don't know what to explore that it can resolve that... i think all my parameters are correct, i have a, self-signed certificate, that works on other PC, and browsers... maybe the repertory ? what do you put exactly, when you are an a raspberry pi 3, and the folder is "home/pi/domoticz"

**Comment by Allen57** [comment]
Hello, I encountered the same issue with a similar situation (fixed -300 issue, installation on a rpi in a home directory), and actually the folder should be left blank (""), this is probably in case domoticz is not at the root of the given url.

**Comment by adrienvia** [comment]
oh, it worked, that was it, thanks ;) perfect.
